### ISSUE TITLE
Variables defined outside of the macro do not work inside macros

### ISSUE THREAD

**Issue by aramirezreyes** [kdpsingh/Tidier.jl#39] opened 2023-03-06 17:54 UTC
Hi!

Thanks for the package! I took it for a spin this morning and noticed variables outside of the scope of the macro are not correctly resolved inside macros. This includes constants like pi.

```julia
using DataFrames, Tidier

a = DataFrame(A = 1:5, B = 'a':'e')
hehe = 2
@chain a begin
    @mutate c = hehe*A
end
```

Which throws:

```julia
ArgumentError: column name "hehe" not found in the data frame; existing most similar names are: "A" and "B"

Stacktrace:
  [1] lookupname
```

This also happens with global constants.

```julia
using DataFrames, Tidier

a = DataFrame(A = 1:5, B = 'a':'e')
@chain a begin
    @mutate c = pi*A
end
```

```julia
using DataFrames, Tidier
global toto=5
a = DataFrame(A = 1:5, B = 'a':'e')
@chain a begin
    @mutate c = toto*A
end
```

Versions:
```julia
Julia Version 1.9.0-beta4
Commit b75ddb787ff (2023-02-07 21:53 UTC)
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 256 × AMD EPYC 7713 64-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, znver3)
  Threads: 9 on 256 virtual cores
Environment:
  LD_LIBRARY_PATH = /opt/nvidia/hpc_sdk/Linux_x86_64/22.5/math_libs/11.7/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/11.7/extras/CUPTI/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/11.7/extras/Debugger/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/11.7/nvvm/lib64:/opt/nvidia/hpc_sdk/Linux_x86_64/22.5/cuda/11.7/lib64:/opt/cray/pe/papi/6.0.0.16/lib64:/opt/cray/pe/gcc/11.2.0/snos/lib64:/opt/cray/libfabric/1.15.2.0/lib64
  JULIA_REVISE_POLL = 1
  JULIA_NUM_THREADS = 8
  ```

and

```julia
[f0413319] Tidier v0.4.1
```

**Comment by kdpsingh** [comment] 2023-03-06 17:58
Thanks for catching this. Tidy expressions make this tricky because the package doesn't explicitly use symbols for columns of data.

I can think of a few ways to handle global constants. Let me review and will reply with a proposed solution that works within the context of the package.

**Comment by aramirezreyes** [comment] 2023-03-06 18:09
Just updated the issue because it seems that all the variables outside of the macro are not resolved

**Comment by aramirezreyes** [comment] 2023-03-06 18:26
Ok, reconsidering, I think I may close this if you agree as [interpolation](https://kdpsingh.github.io/Tidier.jl/dev/examples/generated/UserGuide/interpolation/) sorry for the noise!

**Comment by kdpsingh** [comment] 2023-03-06 18:31
Thanks for solving. While interpolation should work (at least for user-defined globals), it seems like it's not working in this case. That said, interpolation was originally envisioned to handle interpolation of column names from symbols, although I recently extended it to cover values.

Here's a way that will work for both built-in globals (like `pi` and user-defined globals.

```julia
using Tidier

global toto=5

a = DataFrame(A = 1:5, B = 'a':'e')

@chain a begin
    @mutate C = Main.toto * A
end

@chain a begin
    @mutate C = Main.pi * A
end
```

I'll close this issue, but if that doesn't work let me know. At some point, I'll revisit interpolation as a potential solution to this because I agree that interpolation should work.

The key thing here is that *tidy expressions* by default refer to column names, so to refer to variables outside of the data frame, you need to prefix them with the environment (`Main.A`) or use interpolation (although admittedly that fails here, which I will look at).

**Comment by kdpsingh** [comment] 2023-03-06 18:36
Actually, before closing, I think this is a great example of something we should add to the documentation. Will close this out after the docs are updated.

**Comment by aramirezreyes** [comment] 2023-03-06 18:39
Sounds good. Thanks!

**Comment by kdpsingh** [comment] 2023-03-08 02:14
I figured out why I was getting an error with `!!` interpolation. I had the wrong version of Tidier!

Note to self: Pkg.add() doesn't automatically update the package but Pkg.update() does. So yes, both of your examples should work using `!!toto` or `!!pi`.

I'm still going to present the `Main.pi` example because it may be useful. But otherwise I'm glad that this works as designed.

**Closed** 2023-03-10 07:07 UTC
